### ISSUE TITLE
FFB plugin is a git sub project

### ISSUE THREAD

**Issue by michurebmann** [Dechode/Open-Throttle#29] opened 2023-05-05 17:19 UTC
so every time i load the dev branch i have to manually drop back in the SDL2 and the libffb in to bin folder, and bin is not even existing.
the only thing is a .git file from your sub git. so there should be the libs instead a sub git project.
i cannot even commit this changes in my project. i think because of the .git file it is som kind of ignored in staging....

**Comment by Dechode** [comment] 2023-05-05 19:02
Yes the ffbplugin is a submodule by design. You need to do: git submodule update --init in the Godot-FFB-SDL directory so it pulls the files of the submodule. Then there should all of the files of the submodule. Changes are done to the submodule project itself if needed.

**Comment by michurebmann** [comment] 2023-05-05 19:20
and that have to do everyone who download the repo?

**Comment by Dechode** [comment] 2023-05-05 19:26
Yes that is correct. There is a .gitignore file in the bin/ folder so once you have initialized the submodule, you should not be required to  drop the dll:s in there every time you change branches.  That is, if the branch has the ffb-plugin PR already merged.

**Comment by michurebmann** [comment] 2023-05-05 20:03
sorry for being dumb.....

so i have now this "sub module" set up
https://github.com/Dechode/Godot-FFB-SDL

and in godot it looks like this:
![submodule](https://user-images.githubusercontent.com/29509697/236557604-17b7e40e-4a9e-4542-9024-078d115bf7ce.PNG)

is that correct? i dont think so....

a had to put the bins once in it because it was empty...

but now git wants to stage all the files eccept the ones in the bin folder,
so when i would merge the dev now in to my feature, all of this in the picture would be in my feature branch

how on earth should one widhout git knowledge test the open-throttle project ever?

**Comment by Dechode** [comment] 2023-05-05 21:47
That looks right. Idea is we would never have binaries in github, only source code. It is still quite easy to drop the ffb plugin binaries to the right folders.  I have not yet made binaries for the current godot4 branch here on github though. I could make them available tomorrow. 

Once this project is at playable state i will start to provide release builds for the game as well. That would include everything you need just double click on the executable and play.

**Closed** 2023-05-05 22:00 UTC
